function initialize ()
	dofile ( 'core/azCoreGlobal.lua'   		)
	dofile ( 'core/azCoreLinkedList.lua'    )
	dofile ( 'core/azCoreTools.lua'         )
	dofile ( 'core/azCoreImages.lua'        )
	dofile ( 'core/azCoreModules.lua'       )
	dofile ( 'core/azCoreScene.lua'         )
	dofile ( 'core/azCoreSceneModules.lua'  )
	dofile ( 'core/azCoreGameObject.lua'   	)
	dofile ( 'core/azCoreGame.lua'    		)
	dofile ( 'core/azCoreGroup.lua'   		)
	dofile ( 'core/azCoreParticle.lua'      ) 
	dofile ( 'core/azCoreSound.lua'         ) 
	dofile ( 'core/azCoreDataManager.lua'   ) 
	dofile ( 'core/azCoreFonts.lua'         ) 
	dofile ( 'core/azCoreText.lua'          ) 
	dofile ( 'core/azCoreBilling.lua'       ) 
	dofile ( 'core/azCoreInitialize.lua'    )
end